# Generated by Django 2.1.10 on 2019-07-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_num', models.IntegerField(default=0, verbose_name='用例数')),
                ('case_pass_num', models.IntegerField(default=0, verbose_name='用例通过数')),
                ('case_fail_num', models.IntegerField(default=0, verbose_name='用例失败数')),
                ('case_skip_num', models.IntegerField(default=0, verbose_name='用例跳过数')),
                ('api_pass_num', models.IntegerField(default=0, verbose_name='API通过数')),
                ('api_fail_num', models.IntegerField(default=0, verbose_name='API失败数')),
                ('api_error_num', models.IntegerField(default=0, verbose_name='API异常数')),
                ('elapsed_time', models.FloatField(verbose_name='执行时间')),
                ('start_time', models.FloatField(verbose_name='开始时间')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '调试'), (2, '异步'), (3, '定时'), (4, 'auto')], verbose_name='类型')),
                ('project', models.IntegerField(verbose_name='项目ID')),
            ],
            options={
                'verbose_name': '接口自动化数据收集',
                'verbose_name_plural': '接口自动化数据收集',
                'db_table': 'Data',
            },
        ),
    ]
