# Generated by Django 2.1.10 on 2019-07-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollection',
            name='elapsed_time',
            field=models.DurationField(verbose_name='执行时间'),
        ),
    ]
