# Generated by Django 2.1.10 on 2019-07-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner_collection', '0002_auto_20190716_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollection',
            name='elapsed_time',
            field=models.IntegerField(verbose_name='执行时间'),
        ),
    ]
