# Generated by Django 2.1.10 on 2019-07-18 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190718_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users_userprofile_related', related_query_name='users_userprofiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
